### ISSUE TITLE
vite-plugin-eslint 裡的設定

### ISSUE THREAD

**Issue by MollyLin** [mukiwu/vue3-vite-typescript-tailwind-eslint#1]
哈囉大大您好:

我是拜讀您的 Blog 這篇文章[用 Vue3 + Vite + TypeScript + TailwindCSS + ESLint 新增專案](https://muki.tw/tech/vue/vue3-vite-typescript-tailwindcss-eslint-template/)來的，在研讀 code 時發現 `vite-plugin-eslint` 這個模組的 `Options` 裡的 `cache` 預設值即為 `false` (Ref: https://github.com/gxmari007/vite-plugin-eslint#cache) ，想說是否不需另外特別在此指定為 `false` ？

有理解錯誤的話請糾正 > < 感謝指教~

https://github.com/mukiwu/vue3-vite-typescript-tailwind-eslint/blob/48656b0b0373268b97f52b6ca761ee645285366d/vite.config.ts#L10

**Comment by mukiwu** [comment]
不好意思現在才看到 QAQ
是的，如果預設值為 `false`，就不需要特別指定了，謝謝！
